"""Corpus v2 de la commande vocale : commandes (avec {E} = mot d'éveil) et phrases
de TV / conversation qui ne doivent RIEN déclencher.

Les négatifs sont écrits exprès pleins de nos mots (télé, films, jeux, bureau,
gauche, retour, aide, éteins, réglages, netflix…) et des morceaux des mots d'éveil
candidats (salut, dis, ok, hé, prénoms, et même « hub » dans son sens courant).
"""

COMMANDES_FR = [
    ("{E}, lance la télé.", "tv"), ("{E}, télévision.", "tv"), ("{E}, les films.", "tv"), ("{E}, Kodi.", "tv"),
    ("{E}, jeux.", "gaming"), ("{E}, jouer.", "gaming"), ("{E}, bureau.", "bureau"), ("{E}, ordinateur.", "bureau"),
    ("{E}, travailler.", "bureau"), ("{E}, éteins.", "eteindre"), ("{E}, éteins tout.", "eteindre"),
    ("{E}, paramètres.", "reglages"), ("{E}, réglages.", "reglages"), ("{E}, aide.", "aide"),
    ("{E}, retour.", "retour"), ("{E}, accueil.", "retour"), ("{E}, retour à l'accueil.", "retour"),
    ("{E}, gauche.", "gauche"), ("{E}, à droite.", "droite"), ("{E}, en haut.", "haut"), ("{E}, en bas.", "bas"),
    ("{E}, valide.", "ok"), ("{E}, ouvre.", "ok"), ("{E}, thème clair.", "theme:clair"), ("{E}, thème sombre.", "theme:sombre"),
    ("{E}, la météo.", "meteo"), ("{E}, changer de profil.", "profils"), ("{E}, mets les jeux.", "gaming"),
    ("{E}, ouvre les réglages.", "reglages"), ("{E}, va sur le bureau.", "bureau"),
    (("{E}.", "Télé."), "tv"), (("{E}.", "Jeux."), "gaming"), (("{E}.", "Retour."), "retour"),
    (("{E}.", "Bureau."), "bureau"), (("{E}.", "Thème sombre."), "theme:sombre"), (("{E}.", "Météo."), "meteo"),
]
WEB_FR = [
    ("{E}, lance Netflix.", "web:netflix"), ("{E}, YouTube.", "web:youtube"), ("{E}, mets France Télé.", "web:francetv"),
    ("{E}, Disney plus.", "web:disneyplus"), ("{E}, ouvre Prime Vidéo.", "web:primevideo"), ("{E}, Canal plus.", "web:canalplus"),
    ("{E}, va sur Twitch.", "web:twitch"), ("{E}, Arte.", "web:arte"), ("{E}, lance GeForce Now.", "web:geforcenow"),
    ("{E}, Xbox.", "web:xcloud"), ("{E}, Booster.", "web:boosteroid"), ("{E}, lance Steam.", "web:steam"),
    ("{E}, Moonlight.", "web:moonlight"), (("{E}.", "Netflix."), "web:netflix"),
]

COMMANDES_EN = [
    ("{E}, launch the TV.", "tv"), ("{E}, television.", "tv"), ("{E}, movies.", "tv"), ("{E}, Kodi.", "tv"),
    ("{E}, games.", "gaming"), ("{E}, play.", "gaming"), ("{E}, desktop.", "bureau"), ("{E}, computer.", "bureau"),
    ("{E}, turn off.", "eteindre"), ("{E}, shut down the hub.", "eteindre"), ("{E}, settings.", "reglages"),
    ("{E}, help.", "aide"), ("{E}, go back.", "retour"), ("{E}, back to the hub.", "retour"), ("{E}, home.", "retour"),
    ("{E}, left.", "gauche"), ("{E}, right.", "droite"), ("{E}, up.", "haut"), ("{E}, down.", "bas"),
    ("{E}, select.", "ok"), ("{E}, open.", "ok"), ("{E}, light theme.", "theme:clair"), ("{E}, dark mode.", "theme:sombre"),
    ("{E}, weather.", "meteo"), ("{E}, switch profile.", "profils"),
    (("{E}.", "TV."), "tv"), (("{E}.", "Games."), "gaming"), (("{E}.", "Go back."), "retour"),
    (("{E}.", "Desktop."), "bureau"), (("{E}.", "Dark theme."), "theme:sombre"),
]
WEB_EN = [
    ("{E}, launch Netflix.", "web:netflix"), ("{E}, YouTube.", "web:youtube"), ("{E}, open Prime Video.", "web:primevideo"),
    ("{E}, Disney plus.", "web:disneyplus"), ("{E}, Twitch.", "web:twitch"), ("{E}, GeForce Now.", "web:geforcenow"),
    ("{E}, Xbox cloud.", "web:xcloud"), ("{E}, Steam.", "web:steam"), ("{E}, Moonlight.", "web:moonlight"),
]

NEGATIFS_FR = [
    "Ce soir à la télé, un grand film d'aventure.", "Retour sur les grands titres de l'actualité.",
    "Le gouvernement a présenté ses nouvelles mesures ce matin.", "Les paramètres de la loi ont changé cette année.",
    "Le président de la République s'exprimera à vingt heures.", "À gauche comme à droite, les réactions ne se sont pas fait attendre.",
    "L'opposition demande le retour du texte à l'Assemblée.", "Les prix de l'énergie sont repartis à la hausse.",
    "Le trafic est très perturbé sur l'autoroute du Sud.", "Une grève est prévue jeudi dans les transports.",
    "Le ministre a quitté son bureau sous les applaudissements.", "L'aéroport de Roissy reste le premier hub d'Air France.",
    "Lyon veut devenir un hub européen de la logistique.", "Ce nouveau hub numérique accueillera cinquante entreprises.",
    "Les enquêteurs sont retournés sur les lieux du drame.", "La justice a rendu son verdict en fin de journée.",
    "Des milliers de manifestants ont défilé dans le calme.", "La réforme des retraites revient en débat au Sénat.",
    "Le chômage a légèrement baissé au dernier trimestre.", "Les agriculteurs bloquent toujours plusieurs routes.",
    "Le bilan de l'incendie s'est encore alourdi.", "Les secours sont intervenus rapidement sur place.",
    "Une aide exceptionnelle sera versée aux familles.", "L'aide au logement va être revalorisée en janvier.",
    "Le sommet européen s'ouvre demain à Bruxelles.", "Les négociations reprendront la semaine prochaine.",
    "Le Premier ministre a répondu aux questions des députés.", "La cour d'appel a confirmé la condamnation.",
    "Salut à tous, et bienvenue dans ce journal.", "Bonsoir et bienvenue, voici les titres de ce soir.",
    "Tout de suite, direction la Bretagne pour notre reportage.", "On retrouve notre envoyée spéciale sur place.",
    "Merci pour ces précisions, et à tout de suite.", "Dis-moi, qu'est-ce qui a changé depuis hier ?",
    "Restez avec nous, la suite du journal après la publicité.",
    "Il fera beau aujourd'hui sur toute la France.", "La météo de demain s'annonce pluvieuse dans l'ouest.",
    "Quel temps fera-t-il ce week-end ? On fait le point.", "Les températures sont en baisse sur la moitié nord.",
    "Des orages sont attendus en fin de journée.", "Le soleil reviendra dès mercredi en Méditerranée.",
    "Attention au verglas sur les routes en altitude.", "Un vent fort soufflera sur les côtes de la Manche.",
    "Il fait très chaud, pensez à bien vous hydrater.", "La neige tombera au-dessus de mille mètres.",
    "Vigilance orange pour les pluies et les inondations.", "Les nuages resteront bas toute la matinée.",
    "Le club de football a gagné le match.", "Les jeux olympiques commencent demain matin.",
    "Les jeux paralympiques ont battu des records d'audience.", "Il frappe du pied gauche, et c'est le but !",
    "Centre de la droite, tête, et le ballon passe au-dessus.", "Le retour de la star sur les terrains est attendu.",
    "L'équipe de France joue ce soir contre l'Italie.", "Le Tour de France arrive au sommet de l'Alpe d'Huez.",
    "Le match retour aura lieu dans quinze jours.", "Il est hors jeu, l'arbitre annule le but.",
    "Carton rouge pour le défenseur, c'est sévère.", "Quel temps de jeu pour ce jeune attaquant ?",
    "Ils ont joué en haut du tableau toute la saison.", "Le champion du monde a éteint tout suspense.",
    "Tir en bas à gauche, le gardien ne peut rien faire.", "La finale du tournoi se jouera dimanche.",
    "Un doublé pour l'attaquant, qui retrouve la forme.", "Le rugby français est au sommet de son art.",
    "Victoire écrasante, trois buts à zéro.", "Le public se lève, quelle ambiance dans le stade !",
    "Profitez de nos offres exceptionnelles jusqu'à dimanche.", "Nouveau : la télévision connectée à prix mini.",
    "Découvrez les meilleurs jeux vidéo de l'année.", "Un bureau ergonomique pour travailler chez vous.",
    "Paramétrez votre box en quelques clics.", "Changez d'opérateur, gardez votre numéro.",
    "Avec notre application, gérez vos comptes où que vous soyez.", "Le goût du vrai, depuis mille neuf cent vingt.",
    "Offre valable dans les magasins participants.", "Pour votre santé, mangez au moins cinq fruits et légumes par jour.",
    "Abonnez-vous et regardez vos films en illimité.", "Ce week-end, tout le rayon télé est à moins trente pour cent.",
    "Un ordinateur portable léger pour étudier partout.", "Salut les gourmands, voici notre nouvelle recette.",
    "Ok Google, c'est quoi la recette des crêpes ?", "Dis Siri, mets un minuteur de dix minutes.",
    "Alexa, allume la lumière du salon.",
    "Retourne-toi lentement et lève les mains.", "Je t'avais dit de ne jamais revenir ici.",
    "On n'a plus le temps, il faut partir tout de suite.", "Tourne à gauche au prochain carrefour !",
    "Ils sont en haut, montez vite !", "Éteins la lumière, ils arrivent.", "Ouvre la porte, c'est la police !",
    "Salut, ça faisait longtemps.", "Dis-moi la vérité, pour une fois.", "D'accord, on fait comme tu veux.",
    "Hé, attends-moi !", "Au secours, aidez-moi !", "Je ne retournerai jamais dans cette maison.",
    "Tu as vu ce qu'il y a dans le bureau du directeur ?", "Le jeu est terminé, tu as perdu.",
    "C'est un jeu dangereux auquel tu joues.", "Reste en bas, je m'occupe de tout.",
    "Valide ton ticket avant de monter dans le train.", "Je t'aime, tu le sais bien.", "Où étais-tu cette nuit ?",
    "Laisse tomber, ce n'est pas important.", "Il faut qu'on parle, c'est sérieux.", "Je reviens dans cinq minutes.",
    "Tu crois vraiment qu'il va revenir ?", "Hubert, tu m'entends ? Réponds-moi !", "Mais Hubert, qu'est-ce que tu fais là ?",
    "Commandant, le vaisseau est en approche.", "Fermez les écoutilles, on plonge !", "Le trésor est caché sous le vieux chêne.",
    "Qui a tué le docteur dans la bibliothèque ?", "Je vous demande de sortir de mon bureau.", "Rendez-moi mon enfant !",
    "La mission est un succès, retour à la base.", "Retour vers le futur est un film culte.",
    "Mesdames et messieurs, le spectacle va commencer.", "Il était une fois, dans un pays lointain, une princesse.",
    "Et ils vécurent heureux jusqu'à la fin des temps.", "Allez, on y va, on va être en retard.",
    "Tu es sûr de vouloir éteindre la machine ?", "Les paramètres du système ont été modifiés.",
    "Accès refusé, veuillez réessayer.", "Bienvenue à bord, veuillez attacher vos ceintures.",
    "Dans la savane, le lion guette sa proie.", "Les manchots se regroupent pour affronter le froid.",
    "Cette cathédrale a été construite au treizième siècle.", "Le chef ajoute une pincée de sel et un filet d'huile.",
    "Coupez les légumes en petits dés.", "Faites cuire à feu doux pendant vingt minutes.",
    "Notre candidat a choisi le thème de l'histoire.", "Le thème de l'émission est plutôt sombre.",
    "Question suivante, pour mille euros.", "Bonne réponse ! Vous passez au tour suivant.",
    "Le public a voté, et c'est la chanteuse qui l'emporte.", "Ce soir, nos candidats doivent rénover une cuisine.",
    "La maison a été entièrement rénovée en six semaines.", "Ils ont acheté une ferme au fond de la Creuse.",
    "Les archéologues ont découvert un site exceptionnel.", "Voici comment les abeilles fabriquent leur miel.",
    "La planète compte désormais huit milliards d'habitants.", "Le jeu télévisé préféré des Français fête ses trente ans.",
    "Et maintenant, place au grand jeu de l'été.", "Salut les copains, on se retrouve pour un nouvel épisode.",
    "Coucou tout le monde, aujourd'hui on teste des jeux.", "Abonnez-vous à la chaîne et activez la cloche.",
    "Dans cette vidéo, je vous montre mon bureau gaming.", "On passe à la partie suivante du jeu.",
    "Mets le son plus fort, on n'entend rien.", "Le réalisateur a tourné ce film en Islande.",
    "Ce film a reçu la Palme d'or à Cannes.", "Une série à ne pas manquer sur votre télé.",
    "L'acteur retrouve son rôle pour une dernière saison.", "Le dessin animé commence dans cinq minutes.",
    "On regarde un film ce soir ?", "Aide-moi à porter ces cartons.", "Tu peux m'aider à mettre la table ?",
    "Éteins la lumière, s'il te plaît.", "Ouvre la fenêtre, il fait chaud.", "Les enfants aiment jouer dehors.",
    "Il faut valider le formulaire en haut de la page.", "Il est retourné au bureau après la réunion.",
    "Tournez à gauche, puis à droite au rond-point.", "Salut, tu vas bien ?", "Salut, je suis rentré !",
    "Salut maman, je passe ce soir.", "Salut, tu as vu mes clés ?", "Dis, tu as pensé au pain ?", "Dis donc, il est tard.",
    "Dis-moi ce que tu veux manger.", "Dis bonjour à ta grand-mère.", "Ok, j'arrive dans deux minutes.",
    "Ok, d'accord, on fait ça demain.", "Okay, ça marche pour moi.", "Hé, tu as vu l'heure ?", "Bon, on mange quoi ce soir ?",
    "Qui a pris la télécommande ?", "La télécommande est sous le coussin.", "Mets la télé moins fort, le bébé dort.",
    "Tu peux éteindre la télé en partant ?", "Éteins tout avant d'aller te coucher.", "Je vais travailler un peu sur l'ordinateur.",
    "Les jeux vidéo, c'est fini pour ce soir.", "Tu as fini tes devoirs avant de jouer ?", "On va au cinéma samedi ?",
    "Quel film tu veux voir ?", "Il y a un match à la télé ce soir.", "Passe-moi le sel, s'il te plaît.",
    "Le dîner est prêt, à table !", "Tu as nourri le chat ?", "N'oublie pas de sortir les poubelles.",
    "Il reste du café dans la cuisine.", "Je suis fatigué, je vais me coucher.", "Bonne nuit, à demain.",
    "Réveille-toi, tu vas être en retard.", "On part en vacances la semaine prochaine.", "Tu as réservé l'hôtel ?",
    "Mon bureau est un vrai désordre.", "Range ta chambre, c'est le bazar.", "Il fait froid, monte le chauffage.",
    "Le wifi ne marche plus, tu peux redémarrer la box ?", "Va voir en haut si ton frère est là.",
    "Descends, le repas est servi.", "C'est en bas à droite, après l'escalier.", "La salle de bain est à gauche.",
    "Retourne dans ta chambre.", "À quelle heure tu rentres ce soir ?", "Je te rappelle plus tard.",
    "Mamie arrive dimanche pour déjeuner.", "Tu as vu le dernier épisode ?", "Ne me raconte pas la fin !",
    "Quel temps il fait dehors ?", "Prends un parapluie, il va pleuvoir.", "Le chien veut sortir.",
    "Où est-ce que j'ai mis mes lunettes ?", "Ça sent bon dans la cuisine.", "Tu veux un thé ou un café ?",
    "Hubert vient dîner samedi avec sa femme.", "Salut Hubert, entre donc !", "J'ai changé les paramètres du téléphone.",
    "Il faut régler l'heure du four.", "Les réglages de la voiture sont à refaire.", "Tu peux baisser le son de la télévision ?",
    "Profite bien de ta soirée.", "On se fait une partie de cartes ?", "C'est à qui de jouer ?",
    "J'ai gagné, tu me dois un gâteau !", "Arrête de tricher !", "Allez, au lit les enfants.",
    "Tu m'aides à plier le linge ?", "J'ai besoin d'aide pour le dossier.", "Aide ta sœur à ranger ses jouets.",
    "Ouvre les volets, il fait nuit ici.", "Ferme la porte, il y a un courant d'air.", "La lumière du couloir ne s'éteint plus.",
    "Le retour du train est prévu à dix-huit heures.", "On est de retour à la maison.", "Accueille bien nos invités.",
    "Merci pour l'accueil, c'était parfait.", "Le profil de ce candidat me plaît beaucoup.", "Change de chaîne, c'est nul.",
    "Remets la chaîne d'avant.", "Il y a quoi sur la deux ?", "Zappe, il y a de la pub.",
    "On a fait un super jeu de société hier.", "Mon ordinateur est encore en panne.", "Le travail, c'est la santé.",
    "Je travaille à la maison demain.", "Il faut que je termine ce rapport.", "Ton téléphone sonne !",
    "Qui est à la porte ?", "C'est le facteur, il a un colis.", "Tu as payé la facture d'électricité ?",
    "On pourrait repeindre le salon en clair.", "Je préfère le mode sombre sur mon téléphone.", "Ce thème est trop clair pour moi.",
    "Tu peux ouvrir ce pot de confiture ?", "Le lave-vaisselle a fini.", "Mets les assiettes dans le placard du haut.",
    "Les verres sont en bas à gauche.", "La voiture est garée devant.", "Tu as fermé la voiture à clé ?",
    "On se voit demain au bureau.", "Bonne journée, et bon courage !", "Joyeux anniversaire, mon chéri !",
    "Souffle les bougies !", "Qu'est-ce qu'on regarde ?", "Mets un dessin animé pour les petits.",
    "Encore un épisode et on éteint.", "Tu as vu ce but hier soir ?", "Ils jouent bien cette année.",
    "Mon jeu préféré sort vendredi.", "Je te prête ma manette.", "La console est branchée sur la télé du salon.",
    "Le son de la télé grésille.", "Salut, c'est moi, ouvre-moi.", "Dis, on commande une pizza ?",
    "Ok, on commande une pizza.", "Hé, c'est ma place sur le canapé !", "Pousse-toi un peu, je ne vois rien.",
    "Ça commence, taisez-vous !", "Chut, j'écoute les informations.", "Il parle trop vite, ce présentateur.",
    "Je n'aime pas cette émission.", "Mets les sous-titres, s'il te plaît.", "On met la version originale ?",
    "Le film dure trois heures, c'est long.", "Il est déjà minuit, on arrête là.", "Demain, on se lève tôt.",
    "Tu viens marcher avec moi ?", "La boulangerie ferme à dix-neuf heures.", "On invite les voisins samedi ?",
    "Le jardin a besoin d'être arrosé.", "J'ai trouvé un nouveau travail !", "Félicitations, c'est une super nouvelle.",
    "Tu m'as fait peur !", "Je plaisantais, ne t'inquiète pas.", "Il faut qu'on parle de nos vacances.",
    "Et si on allait à la mer ?", "Je préfère la montagne.", "Les enfants, on part dans dix minutes.",
    "Mets tes chaussures et ton manteau.", "N'oublie pas ton cartable.", "Tu as bien travaillé à l'école ?",
    "La maîtresse est contente de toi.", "Qu'est-ce que tu as appris aujourd'hui ?", "On a joué au ballon dans la cour.",
    "Je peux regarder la télé ?", "Juste un dessin animé, et au lit.", "Maman, il m'a tapé !",
    "Arrêtez de vous disputer.", "Faites la paix, tous les deux.", "Qui veut du dessert ?",
    "Il reste de la glace au congélateur.", "Hubert a appelé, il rappellera ce soir.", "Un salut rapide avant de partir.",
    "Il a fait un signe de la main pour dire salut.", "Ce hub USB ne marche plus.", "Branche le disque sur le hub.",
    "Dis voir, c'est quoi ce bruit ?", "Salut la compagnie !", "Ok pour moi, et toi ?", "Je dis ça, je dis rien.",
    "Dis-lui de rappeler plus tard.", "Salut, à plus tard !", "Aide-moi, je n'y arrive pas.",
    "Tu peux m'aider avec l'ordinateur ?", "J'ai éteint le chauffage en partant.", "Retour à la case départ.",
    "À droite toute !", "En haut de l'affiche ce soir, un grand concert.", "Direction le bureau de vote.",
    "Les résultats seront connus à vingt heures.", "Le candidat de gauche arrive en tête.", "La droite conserve la mairie.",
    "La météo est clémente pour ce week-end de départs.", "Changer de profil sur le réseau social est facile.",
    "Tu peux lancer la machine à laver ?", "Lance le dé, c'est ton tour.", "Mets la table, on mange.",
    "Va sur la terrasse, il fait beau.", "Ouvre les cadeaux !", "Le bureau de poste est fermé le lundi.",
    "Les jeux sont faits, rien ne va plus.", "Qui veut jouer aux cartes ?", "Je suis au travail jusqu'à six heures.",
    # Streaming : les noms des services dans la bouche de la TV et du salon.
    "La nouvelle saison arrive sur Netflix vendredi.", "Tu as vu cette vidéo sur YouTube ?",
    "Ce soir sur Arte, un documentaire sur les océans.", "Retrouvez tous nos programmes sur France Télévisions.",
    "Le match est diffusé sur Canal plus.", "Disney plus annonce une hausse de ses tarifs.",
    "Il fait des lives sur Twitch tous les soirs.", "J'ai acheté ce jeu en promotion sur Steam.",
    "Prime Vidéo lance une nouvelle série policière.", "La nouvelle Xbox est plus puissante.",
    "Mets Netflix, on finit la série.", "Lance YouTube pour les enfants.", "Amazon livre le colis demain.",
    "Il a un booster pour sa voiture.", "Le clair de lune, moonlight en anglais.",
]

NEGATIFS_EN = [
    "Tonight on TV, a great adventure movie.", "The Olympic games start tomorrow morning.",
    "He went back to the office after the meeting.", "Turn left, then right at the roundabout.",
    "The theme of the show is quite dark.", "Help me carry these boxes.",
    "Turn off the light, please.", "The settings of the law changed this year.",
    "Shall we watch a movie tonight?", "It will be sunny today across the country.",
    "The club won the match.", "Open the window, it is hot.",
    "Back to the headlines.", "Select the form at the top of the page.", "Kids love to play outside.",
    "Hey, how are you doing?", "Okay, I'll be there in five minutes.", "Hey, wait for me!",
    "The airport is the main hub for the airline.", "Plug the drive into the USB hub.",
    "Good evening and welcome to the news.", "The president will speak tonight at eight.",
    "Heavy rain is expected in the north.", "What's the weather like tomorrow?",
    "The team is playing at home this weekend.", "He shoots with his left foot, and it's a goal!",
    "Can you help me with my homework?", "Where is the remote control?",
    "Turn the TV down, the baby is sleeping.", "Let's play a board game.",
    "I have to work late tonight.", "My computer crashed again.",
    "Go upstairs and get your brother.", "The kitchen is on the right.",
    "Welcome home, honey!", "Switch the channel, this is boring.",
    "Okay Google, what time is it?", "Hey Siri, set a timer.", "Alexa, play some music.",
    "The new video game comes out on Friday.", "Open the door, it's the police!",
    "Get back here right now!", "Up, up and away!", "Down the hall and to the left.",
    "Dark chocolate is my favorite.", "Light travels faster than sound.",
    "Forecast: sunny with a chance of clouds.", "Users can change their profile picture.",
    "Shut down the engines, we have landed.", "Go home, you're drunk.",
    "The new season drops on Netflix this Friday.", "I watched that video on YouTube.",
    "He streams on Twitch every night.", "I bought this game on sale on Steam.",
]
